### ISSUE TITLE
Update Grakn dependency in client-java, python, nodejs, workbase, docs, and examples

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4890]
This ticket should be done after https://github.com/graknlabs/grakn/issues/4894

- The syncing should be done in a job in the workflow named `ci`
- The job should only be ran when there is a new commit in `master`.
- The job updates the Grakn dependencies of `client-java` located in the `development` branch
- We should be able to generalise the script used for docs so we can reuse it, instead of creating a new one which would end up looking similar

We've already done something similar for docs, therefore the job should be somewhat alike:
```
jobs:
  dependency-update:
    machine: true
    steps:
      - checkout
      - run:
          name: Update Grakn dependency in client-java, python, nodejs, workbase, docs, and examples
          command: |
            mkdir docs
            cd docs
            bazel run @graknlabs_grabl//sync:dependency-update -- --dependency grakn:master --user client-java:development client-python:development client-nodejs:development workbase:development 
 docs:development examples:development

...

workflows:
  ci:
    jobs:

      ...

      # sync client-java/development to the latest grakn version
      - dependency-update:
          filters:
            branches:
              only: master
          requires:
              ...
```
