### ISSUE TITLE
Update Grakn dependency in client-python

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4893]
This ticket should be done after https://github.com/graknlabs/grakn/issues/4894

- The syncing should be done in a job in the workflow named `ci`
- The job should only be ran when there is a new commit in `master`.
- The job updates the Grakn dependencies of `client-python` located in the `development` branch
- We should be able to generalise the script used for docs so we can reuse it, instead of creating a new one which would end up looking similar

We've already done something similar for docs, therefore the job should be somewhat alike:
```
jobs:
  client-python-update:
    machine: true
    steps:
      - checkout
      - run:
          name: Sync client-python/development to the latest Grakn version
          command: |
            mkdir docs
            cd docs
            python ../.circleci/client-python-update.py

...

workflows:
  ci:
    jobs:

      ...

      # sync client-python/development to the latest grakn version
      - client-python-update:
          filters:
            branches:
              only: master
          requires:
              ...
```
